## YAML Template.
---
services:

  frontend:
    container_name: angular_front
    build:
      context: ../buddy-adopt
      dockerfile: Dockerfile
    ports:
      - "4200:80"   # Nginx sirve SPA
    restart: always
    networks:
      - buddy-net

networks:
  buddy-net:
    external: true
